### ISSUE TITLE
Question regarding the runtime dir patch

### ISSUE THREAD

**Issue by soumyaDghosh** [iomezk/snap-mpv#1]
Hi.. the snap mpv wayland can be revoked. As the mpv snap is doing well, is almost similar, except the runtime dir patch. What does it do? Can you explain it to me once?

**Comment by iomezk** [comment]
It's experiment of creating GUI snaps without scripts. This patch is also in use by the rest of my Wayland-only snaps like a screenshot tool `grim` or `wl-clip`.

Another difference is that `mpv-wayland` in --edge use shared ffmpeg snap. I'm trying to promote it because it solves many problems, but with no luck.
https://forum.snapcraft.io/t/allow-global-autoconnect-libavcodec58-core22/36767

**Comment by soumyaDghosh** [comment]
The current mpv snap(one MR needs to be merged) is at a very good position. And as I said you there also, your work has been a duplication. I have added my ffmpeg content snap there, and it works perfectly. Now, I think it'd be great if you can help me create and maintain gstreamer and some other content snaps. Please don't duplicate works. It'll just waste time. Use my ffmpeg sdk snap in all of your snaps and ask for an auto connection in the store. Also, please unlist your mpv, it's of no use any more. Please.

The current mpv manifest can be found here
https://code.launchpad.net/~capecrusader-121/mpv-snap/+git/mpv

@capecrusader-121 is maintaining this.

**Comment by iomezk** [comment]
I have [updated the description of mpv-wayland](https://snapcraft.io/mpv-wayland) and will think about unlisting.

As was said before, any ffmpeg content snap from a trusted publisher will be good. I would like to use it for the official `tor-browser` snap, but the Tor Project most likely will not agree to use a thing that is not managed by Canonical.  
Also there could be stability issues. Changes in sdk snap can even break building (kde framework cases).

**Comment by soumyaDghosh** [comment]
> As was said before, any ffmpeg content snap from a trusted publisher will be good. I would like to use it for the official `tor-browser` snap, but the Tor Project most likely will not agree to use a thing that is not managed by Canonical. Also there could be stability issues. Changes in sdk snap can even break building (kde framework cases).

The KDE issue is a whole different one. It doesn't have a sustainable plan.



> I have [updated the description of mpv-wayland](https://snapcraft.io/mpv-wayland) and will think about unlisting.

Well, is there anything special/better on this wayland only mpv? The current one already works as it should be, and with the PR merging soon, it'll get mpris and screen inhibit control in wayland. BTW, thanks for your efforts.

**Comment by iomezk** [comment]
> Well, is there anything special/better on this wayland only mpv?

- yt-dlp is accessible as a command (capecrusader-121 refused this). It's .pyc-only with build dependencies removed.
- no dependency on `mesa-core22` snap
- ffmpeg built with --toolchain=hardened
- stripped binaries

**Comment by soumyaDghosh** [comment]
> * yt-dlp is accessible as a command (capecrusader-121 refused this). It's .pyc-only with build dependencies removed.

It's there, if you think about yt-dlp separately, then it doesn't make sense, as yt-dlp snap exists.



> * ffmpeg built with --toolchain=hardened
> 
> * stripped binaries

Doesn't make sense, those are made to make the content snap reliable by any random snap. C# and Flutter, often has such problems, with stripped binaries. I already have 4-5 snaps running by others, using my ffmpeg-sdk, and all of them are fine working.

**Comment by iomezk** [comment]
> if you think about yt-dlp separately, then it doesn't make sense, as yt-dlp snap exists.

It's additional 132MB x number of installed revisions. BTW, in mpv-wayland .pyc yt-dlp adds only 4MB

**Comment by soumyaDghosh** [comment]
> > if you think about yt-dlp separately, then it doesn't make sense, as yt-dlp snap exists.
> 
> It's additional 132MB x number of installed revisions. BTW, in mpv-wayland .pyc yt-dlp adds only 4MB

Okay.. thanks for pointing it out. I'll fix it.

**Comment by soumyaDghosh** [comment]
Thanks for using `ffmpeg` content snap.
